-- Práctica Unidad 3 "My Family" (~100, original A1.3). Idempotente.
do $$
begin
  if exists (select 1 from practice_exercises where unit_id = 3) then
    raise notice 'La unidad 3 ya tiene práctica.'; return;
  end if;
  insert into practice_exercises (unit_id, area, level, type, timed, time_limit_seconds, prompt, payload, correct_answer, explanation, xp_reward) values
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a dog. ___ dog is new.', '{"options":["Your","My","Our"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a car. ___ car is small.', '{"options":["His","Her","Your"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a bike. ___ bike is blue.', '{"options":["My","Our","His"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a cat. ___ cat is big.', '{"options":["Her","His","Their"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a pen. ___ pen is nice.', '{"options":["His","My","Our"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a phone. ___ phone is old.', '{"options":["His","Her","Our"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a friend. ___ friend is black.', '{"options":["My","Your","Our"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a book. ___ book is red.', '{"options":["My","Her","Their"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a house. ___ house is fast.', '{"options":["His","Our","My"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a ball. ___ ball is great.', '{"options":["Her","Our","His"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a dog. ___ dog is new.', '{"options":["Your","Our","My"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a car. ___ car is small.', '{"options":["Your","His","Her"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a bike. ___ bike is blue.', '{"options":["My","His","Your"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a cat. ___ cat is big.', '{"options":["Her","Our","Your"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a pen. ___ pen is nice.', '{"options":["His","My","Her"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a phone. ___ phone is old.', '{"options":["My","Her","His"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'I have a friend. ___ friend is black.', '{"options":["His","My","Her"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 1, 'multiple_choice', false, null, 'She has a book. ___ book is red.', '{"options":["Her","His","Your"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 2, 'multiple_choice', false, null, 'I have a house. ___ house is fast.', '{"options":["His","My","Our"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 2, 'multiple_choice', false, null, 'She has a ball. ___ ball is great.', '{"options":["Her","His","Their"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 2, 'multiple_choice', false, null, 'I have a dog. ___ dog is new.', '{"options":["My","Their","Her"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 2, 'multiple_choice', false, null, 'She has a car. ___ car is small.', '{"options":["Our","His","Her"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 2, 'multiple_choice', false, null, 'I have a bike. ___ bike is blue.', '{"options":["My","Their","Her"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 2, 'multiple_choice', false, null, 'She has a cat. ___ cat is big.', '{"options":["His","Our","Her"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'grammar', 2, 'multiple_choice', false, null, 'I have a pen. ___ pen is nice.', '{"options":["Their","Your","My"]}'::jsonb, 'My', 'I → My.', 10),
  (3, 'grammar', 2, 'multiple_choice', false, null, 'She has a phone. ___ phone is old.', '{"options":["Your","Her","Our"]}'::jsonb, 'Her', 'She → Her.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, 'Tu progenitora (mujer) es tu:', '{"options":["sister","father","mother"]}'::jsonb, 'mother', '"mother" = madre.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, 'Tu progenitor (hombre) es tu:', '{"options":["father","mother","brother"]}'::jsonb, 'father', '"father" = padre.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, 'Un niño con tus mismos padres:', '{"options":["uncle","brother","sister"]}'::jsonb, 'brother', '"brother" = hermano.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, 'Una niña con tus mismos padres:', '{"options":["sister","brother","aunt"]}'::jsonb, 'sister', '"sister" = hermana.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, 'La madre de tu madre es tu:', '{"options":["grandmother","aunt","mother"]}'::jsonb, 'grandmother', '"grandmother" = abuela.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, '''brother'' significa:', '{"options":["hermana","padre","hermano"]}'::jsonb, 'hermano', '"brother" = hermano.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, '''sister'' significa:', '{"options":["hermano","hermana","madre"]}'::jsonb, 'hermana', '"sister" = hermana.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, '''mother'' en español:', '{"options":["padre","madre","hijo"]}'::jsonb, 'madre', '"mother" = madre.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, '''father'' en español:', '{"options":["padre","tío","madre"]}'::jsonb, 'padre', '"father" = padre.', 10),
  (3, 'vocabulary', 2, 'multiple_choice', false, null, '''grandmother'' significa:', '{"options":["tía","abuelo","abuela"]}'::jsonb, 'abuela', '"grandmother" = abuela.', 10),
  (3, 'grammar', 3, 'multiple_choice', false, null, '10:15 es:', '{"options":["ten o''clock","half past ten","a quarter past ten"]}'::jsonb, 'a quarter past ten', '10:15 = a quarter past ten.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '11:45 es:', '{"options":["eleven o''clock","a quarter to twelve","half past eleven"]}'::jsonb, 'a quarter to twelve', '11:45 = a quarter to twelve.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '4:00 es:', '{"options":["four o''clock","half past four","a quarter past four"]}'::jsonb, 'four o''clock', '4:00 = four o''clock.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '11:30 es:', '{"options":["a quarter past eleven","eleven o''clock","half past eleven"]}'::jsonb, 'half past eleven', '11:30 = half past eleven.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '2:15 es:', '{"options":["half past two","two o''clock","a quarter past two"]}'::jsonb, 'a quarter past two', '2:15 = a quarter past two.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '9:45 es:', '{"options":["a quarter to ten","half past nine","nine o''clock"]}'::jsonb, 'a quarter to ten', '9:45 = a quarter to ten.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '10:00 es:', '{"options":["half past ten","a quarter past ten","ten o''clock"]}'::jsonb, 'ten o''clock', '10:00 = ten o''clock.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '1:30 es:', '{"options":["half past one","a quarter past one","one o''clock"]}'::jsonb, 'half past one', '1:30 = half past one.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '7:15 es:', '{"options":["a quarter past seven","half past seven","seven o''clock"]}'::jsonb, 'a quarter past seven', '7:15 = a quarter past seven.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '5:45 es:', '{"options":["half past five","a quarter to six","five o''clock"]}'::jsonb, 'a quarter to six', '5:45 = a quarter to six.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '8:00 es:', '{"options":["a quarter past eight","half past eight","eight o''clock"]}'::jsonb, 'eight o''clock', '8:00 = eight o''clock.', 15),
  (3, 'grammar', 3, 'multiple_choice', false, null, '2:30 es:', '{"options":["half past two","two o''clock","a quarter past two"]}'::jsonb, 'half past two', '2:30 = half past two.', 15),
  (3, 'grammar', 3, 'fill_blank', false, null, 'Posesivo: "I have a dog. ___ dog is new."', '{}'::jsonb, 'My', 'I → My.', 15),
  (3, 'grammar', 3, 'fill_blank', false, null, 'Posesivo: "She has a car. ___ car is small."', '{}'::jsonb, 'Her', 'She → Her.', 15),
  (3, 'grammar', 3, 'fill_blank', false, null, 'Posesivo: "I have a bike. ___ bike is blue."', '{}'::jsonb, 'My', 'I → My.', 15),
  (3, 'grammar', 3, 'fill_blank', false, null, 'Posesivo: "She has a cat. ___ cat is big."', '{}'::jsonb, 'Her', 'She → Her.', 15),
  (3, 'grammar', 3, 'fill_blank', false, null, 'Posesivo: "I have a pen. ___ pen is nice."', '{}'::jsonb, 'My', 'I → My.', 15),
  (3, 'grammar', 3, 'fill_blank', false, null, 'Posesivo: "She has a phone. ___ phone is old."', '{}'::jsonb, 'Her', 'She → Her.', 15),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["My","is","black","friend"]}'::jsonb, 'My friend is black', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["is","Her","book","red"]}'::jsonb, 'Her book is red', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["fast","My","is","house"]}'::jsonb, 'My house is fast', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["great","is","Her","ball"]}'::jsonb, 'Her ball is great', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["My","is","dog","new"]}'::jsonb, 'My dog is new', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["car","is","small","Her"]}'::jsonb, 'Her car is small', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["bike","is","My","blue"]}'::jsonb, 'My bike is blue', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["cat","Her","is","big"]}'::jsonb, 'Her cat is big', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["is","pen","nice","My"]}'::jsonb, 'My pen is nice', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["Her","phone","is","old"]}'::jsonb, 'Her phone is old', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["black","is","friend","My"]}'::jsonb, 'My friend is black', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["red","book","Her","is"]}'::jsonb, 'Her book is red', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["My","house","is","fast"]}'::jsonb, 'My house is fast', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["great","is","Her","ball"]}'::jsonb, 'Her ball is great', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["new","My","is","dog"]}'::jsonb, 'My dog is new', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["car","small","Her","is"]}'::jsonb, 'Her car is small', 'Posesivo + sustantivo + to be + adjetivo.', 20),
  (3, 'grammar', 5, 'true_false', true, 20, '''She have a cat'' is correct.', '{}'::jsonb, 'false', 'Lo correcto: She has a cat.', 20),
  (3, 'grammar', 5, 'true_false', true, 20, '''My name is Ana'' is correct.', '{}'::jsonb, 'true', 'Correcto.', 20),
  (3, 'grammar', 5, 'true_false', true, 20, '''His sister is tall'' is correct.', '{}'::jsonb, 'true', 'Correcto.', 20),
  (3, 'grammar', 5, 'true_false', true, 20, '''Her brother are tall'' is correct.', '{}'::jsonb, 'false', 'Lo correcto: Her brother is tall.', 20),
  (3, 'grammar', 5, 'true_false', true, 20, '''Their house is big'' is correct.', '{}'::jsonb, 'true', 'Correcto.', 20),
  (3, 'grammar', 5, 'true_false', true, 20, '''Our teacher are nice'' is correct.', '{}'::jsonb, 'false', 'Lo correcto: Our teacher is nice.', 20),
  (3, 'grammar', 5, 'true_false', true, 20, '''I has a dog'' is correct.', '{}'::jsonb, 'false', 'Lo correcto: I have a dog.', 20),
  (3, 'grammar', 5, 'true_false', true, 20, '''We have a car'' is correct.', '{}'::jsonb, 'true', 'Correcto.', 20),
  (3, 'grammar', 5, 'multiple_choice', true, 20, '9:00 es:', '{"options":["half past nine","nine o''clock","a quarter past nine"]}'::jsonb, 'nine o''clock', '9:00 = nine o''clock.', 20),
  (3, 'grammar', 5, 'multiple_choice', true, 20, '5:30 es:', '{"options":["five o''clock","a quarter past five","half past five"]}'::jsonb, 'half past five', '5:30 = half past five.', 20),
  (3, 'grammar', 5, 'multiple_choice', true, 20, '2:15 es:', '{"options":["two o''clock","a quarter past two","half past two"]}'::jsonb, 'a quarter past two', '2:15 = a quarter past two.', 20),
  (3, 'grammar', 5, 'multiple_choice', true, 20, '7:45 es:', '{"options":["a quarter to eight","half past seven","seven o''clock"]}'::jsonb, 'a quarter to eight', '7:45 = a quarter to eight.', 20),
  (3, 'grammar', 5, 'multiple_choice', true, 20, '3:00 es:', '{"options":["three o''clock","a quarter past three","half past three"]}'::jsonb, 'three o''clock', '3:00 = three o''clock.', 20),
  (3, 'grammar', 5, 'multiple_choice', true, 20, '2:30 es:', '{"options":["a quarter past two","two o''clock","half past two"]}'::jsonb, 'half past two', '2:30 = half past two.', 20),
  (3, 'grammar', 5, 'multiple_choice', true, 20, '6:15 es:', '{"options":["six o''clock","half past six","a quarter past six"]}'::jsonb, 'a quarter past six', '6:15 = a quarter past six.', 20),
  (3, 'grammar', 5, 'multiple_choice', true, 20, '6:45 es:', '{"options":["a quarter to seven","half past six","six o''clock"]}'::jsonb, 'a quarter to seven', '6:45 = a quarter to seven.', 20),
  (3, 'grammar', 6, 'multiple_choice', true, 12, 'He has a house. ___ house is fast.', '{"options":["Their","His","Her"]}'::jsonb, 'His', 'He → His.', 20),
  (3, 'grammar', 6, 'multiple_choice', true, 12, 'They have a ball. ___ ball is great.', '{"options":["Their","His","Her"]}'::jsonb, 'Their', 'They → Their.', 20),
  (3, 'grammar', 6, 'multiple_choice', true, 12, 'He has a dog. ___ dog is new.', '{"options":["His","My","Our"]}'::jsonb, 'His', 'He → His.', 20),
  (3, 'grammar', 6, 'multiple_choice', true, 12, 'They have a car. ___ car is small.', '{"options":["Our","His","Their"]}'::jsonb, 'Their', 'They → Their.', 20),
  (3, 'grammar', 6, 'multiple_choice', true, 12, 'He has a bike. ___ bike is blue.', '{"options":["His","Your","Our"]}'::jsonb, 'His', 'He → His.', 20),
  (3, 'grammar', 6, 'multiple_choice', true, 12, 'They have a cat. ___ cat is big.', '{"options":["My","Their","Her"]}'::jsonb, 'Their', 'They → Their.', 20),
  (3, 'grammar', 6, 'multiple_choice', true, 12, 'He has a pen. ___ pen is nice.', '{"options":["Their","Our","His"]}'::jsonb, 'His', 'He → His.', 20),
  (3, 'grammar', 6, 'multiple_choice', true, 12, 'They have a phone. ___ phone is old.', '{"options":["Her","Our","Their"]}'::jsonb, 'Their', 'They → Their.', 20),
  (3, 'grammar', 6, 'fill_blank', true, 12, 'Posesivo: "He has a friend. ___ friend is black."', '{}'::jsonb, 'His', 'He → His.', 20),
  (3, 'grammar', 6, 'fill_blank', true, 12, 'Posesivo: "They have a book. ___ book is red."', '{}'::jsonb, 'Their', 'They → Their.', 20),
  (3, 'grammar', 6, 'fill_blank', true, 12, 'Posesivo: "He has a house. ___ house is fast."', '{}'::jsonb, 'His', 'He → His.', 20),
  (3, 'grammar', 6, 'fill_blank', true, 12, 'Posesivo: "They have a ball. ___ ball is great."', '{}'::jsonb, 'Their', 'They → Their.', 20),
  (3, 'grammar', 6, 'fill_blank', true, 12, 'Posesivo: "He has a dog. ___ dog is new."', '{}'::jsonb, 'His', 'He → His.', 20),
  (3, 'grammar', 6, 'fill_blank', true, 12, 'Posesivo: "They have a car. ___ car is small."', '{}'::jsonb, 'Their', 'They → Their.', 20);
  raise notice 'Unidad 3: 100 ejercicios sembrados.';
end $$;
