-- Práctica Unidad 2 "My Classroom" (~100 ejercicios, original A1.3). Idempotente.
do $$
begin
  if exists (select 1 from practice_exercises where unit_id = 2) then
    raise notice 'La unidad 2 ya tiene práctica.'; return;
  end if;
  insert into practice_exercises (unit_id, area, level, type, timed, time_limit_seconds, prompt, payload, correct_answer, explanation, xp_reward) values
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ pen"', '{"options":["an","a"]}'::jsonb, 'a', '"pen" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ chair"', '{"options":["an","a"]}'::jsonb, 'a', '"chair" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ teacher"', '{"options":["an","a"]}'::jsonb, 'a', '"teacher" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ dog"', '{"options":["a","an"]}'::jsonb, 'a', '"dog" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ table"', '{"options":["a","an"]}'::jsonb, 'a', '"table" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ door"', '{"options":["an","a"]}'::jsonb, 'a', '"door" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ car"', '{"options":["an","a"]}'::jsonb, 'a', '"car" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ friend"', '{"options":["an","a"]}'::jsonb, 'a', '"friend" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ boy"', '{"options":["a","an"]}'::jsonb, 'a', '"boy" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ banana"', '{"options":["a","an"]}'::jsonb, 'a', '"banana" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ pen"', '{"options":["a","an"]}'::jsonb, 'a', '"pen" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ chair"', '{"options":["a","an"]}'::jsonb, 'a', '"chair" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ teacher"', '{"options":["a","an"]}'::jsonb, 'a', '"teacher" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ dog"', '{"options":["a","an"]}'::jsonb, 'a', '"dog" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ table"', '{"options":["a","an"]}'::jsonb, 'a', '"table" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ door"', '{"options":["an","a"]}'::jsonb, 'a', '"door" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ car"', '{"options":["a","an"]}'::jsonb, 'a', '"car" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 1, 'multiple_choice', false, null, 'Elige: "___ friend"', '{"options":["an","a"]}'::jsonb, 'a', '"friend" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Elige: "___ boy"', '{"options":["an","a"]}'::jsonb, 'a', '"boy" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Elige: "___ banana"', '{"options":["an","a"]}'::jsonb, 'a', '"banana" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Elige: "___ pen"', '{"options":["an","a"]}'::jsonb, 'a', '"pen" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Elige: "___ chair"', '{"options":["a","an"]}'::jsonb, 'a', '"chair" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Elige: "___ teacher"', '{"options":["an","a"]}'::jsonb, 'a', '"teacher" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Elige: "___ dog"', '{"options":["an","a"]}'::jsonb, 'a', '"dog" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Elige: "___ table"', '{"options":["an","a"]}'::jsonb, 'a', '"table" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Elige: "___ door"', '{"options":["a","an"]}'::jsonb, 'a', '"door" empieza con sonido consonante → a.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "book":', '{"options":["books","book","bookes"]}'::jsonb, 'books', 'El plural regular añade -s: books.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "pen":', '{"options":["pens","pen","penes"]}'::jsonb, 'pens', 'El plural regular añade -s: pens.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "pencil":', '{"options":["pencils","pencil","penciles"]}'::jsonb, 'pencils', 'El plural regular añade -s: pencils.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "chair":', '{"options":["chairs","chaires","chair"]}'::jsonb, 'chairs', 'El plural regular añade -s: chairs.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "desk":', '{"options":["deskes","desks","desk"]}'::jsonb, 'desks', 'El plural regular añade -s: desks.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "dog":', '{"options":["dogs","dog","doges"]}'::jsonb, 'dogs', 'El plural regular añade -s: dogs.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "cat":', '{"options":["cat","cats","cates"]}'::jsonb, 'cats', 'El plural regular añade -s: cats.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "table":', '{"options":["table","tablees","tables"]}'::jsonb, 'tables', 'El plural regular añade -s: tables.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "window":', '{"options":["window","windows","windowes"]}'::jsonb, 'windows', 'El plural regular añade -s: windows.', 10),
  (2, 'grammar', 2, 'multiple_choice', false, null, 'Plural de "door":', '{"options":["door","doors","doores"]}'::jsonb, 'doors', 'El plural regular añade -s: doors.', 10),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'varias, cerca: "___ are phones."', '{"options":["That","These","This","Those"]}'::jsonb, 'These', 'varias + cerca = These.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, '1 cosa, cerca: "___ is a book."', '{"options":["This","That","Those","These"]}'::jsonb, 'This', '1 cosa + cerca = This.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'varias, cerca: "___ are pencils."', '{"options":["Those","These","This","That"]}'::jsonb, 'These', 'varias + cerca = These.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, '1 cosa, cerca: "___ is a desk."', '{"options":["This","Those","That","These"]}'::jsonb, 'This', '1 cosa + cerca = This.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'varias, cerca: "___ are cats."', '{"options":["These","That","Those","This"]}'::jsonb, 'These', 'varias + cerca = These.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, '1 cosa, cerca: "___ is a window."', '{"options":["This","Those","These","That"]}'::jsonb, 'This', '1 cosa + cerca = This.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'varias, cerca: "___ are cars."', '{"options":["This","Those","These","That"]}'::jsonb, 'These', 'varias + cerca = These.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, '1 cosa, cerca: "___ is a ball."', '{"options":["This","Those","That","These"]}'::jsonb, 'This', '1 cosa + cerca = This.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'varias, cerca: "___ are pens."', '{"options":["This","These","That","Those"]}'::jsonb, 'These', 'varias + cerca = These.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, '1 cosa, cerca: "___ is a chair."', '{"options":["These","This","That","Those"]}'::jsonb, 'This', '1 cosa + cerca = This.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'varias, cerca: "___ are dogs."', '{"options":["That","Those","These","This"]}'::jsonb, 'These', 'varias + cerca = These.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, '1 cosa, cerca: "___ is a table."', '{"options":["That","These","This","Those"]}'::jsonb, 'This', '1 cosa + cerca = This.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'Plural de "dish":', '{"options":["dish","dishes","dishs"]}'::jsonb, 'dishes', 'Termina en s/sh/ch/x/o → añade -es: dishes.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'Plural de "glass":', '{"options":["glass","glasss","glasses"]}'::jsonb, 'glasses', 'Termina en s/sh/ch/x/o → añade -es: glasses.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'Plural de "potato":', '{"options":["potato","potatos","potatoes"]}'::jsonb, 'potatoes', 'Termina en s/sh/ch/x/o → añade -es: potatoes.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'Plural irregular de "mouse":', '{"options":["mousees","mice","mouses"]}'::jsonb, 'mice', '"mouse" es irregular: mice.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'Plural irregular de "child":', '{"options":["childs","children","childes"]}'::jsonb, 'children', '"child" es irregular: children.', 15),
  (2, 'grammar', 3, 'multiple_choice', false, null, 'Plural irregular de "man":', '{"options":["mans","men","manes"]}'::jsonb, 'men', '"man" es irregular: men.', 15),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["is","a","This","pencil"]}'::jsonb, 'This is a pencil', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["desks","These","are"]}'::jsonb, 'These are desks', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["is","cat","This","a"]}'::jsonb, 'This is a cat', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["These","windows","are"]}'::jsonb, 'These are windows', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["a","is","This","car"]}'::jsonb, 'This is a car', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["These","are","balls"]}'::jsonb, 'These are balls', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["This","is","pen","a"]}'::jsonb, 'This is a pen', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["are","These","chairs"]}'::jsonb, 'These are chairs', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["is","This","a","dog"]}'::jsonb, 'This is a dog', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["are","tables","These"]}'::jsonb, 'These are tables', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["door","is","a","This"]}'::jsonb, 'This is a door', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["phones","These","are"]}'::jsonb, 'These are phones', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["is","a","book","This"]}'::jsonb, 'This is a book', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["are","These","pencils"]}'::jsonb, 'These are pencils', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["desk","This","a","is"]}'::jsonb, 'This is a desk', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["These","are","cats"]}'::jsonb, 'These are cats', 'Demostrativo + verbo to be + objeto.', 20),
  (2, 'grammar', 5, 'true_false', true, 20, '''an apple'' is correct.', '{}'::jsonb, 'true', 'Correcto: apple empieza con vocal.', 20),
  (2, 'grammar', 5, 'true_false', true, 20, '''a apple'' is correct.', '{}'::jsonb, 'false', 'Lo correcto es "an apple".', 20),
  (2, 'grammar', 5, 'true_false', true, 20, '''an book'' is correct.', '{}'::jsonb, 'false', 'Lo correcto es "a book".', 20),
  (2, 'grammar', 5, 'true_false', true, 20, '''a teacher'' is correct.', '{}'::jsonb, 'true', 'Correcto: teacher empieza con consonante.', 20),
  (2, 'grammar', 5, 'true_false', true, 20, '''These is my pen'' is correct.', '{}'::jsonb, 'false', 'Lo correcto es "This is my pen".', 20),
  (2, 'grammar', 5, 'true_false', true, 20, '''Those are books'' is correct.', '{}'::jsonb, 'true', 'Correcto: plural + lejos.', 20),
  (2, 'grammar', 5, 'true_false', true, 20, '''a egg'' is correct.', '{}'::jsonb, 'false', 'Lo correcto es "an egg".', 20),
  (2, 'grammar', 5, 'true_false', true, 20, '''an orange'' is correct.', '{}'::jsonb, 'true', 'Correcto: orange empieza con vocal.', 20),
  (2, 'vocabulary', 5, 'multiple_choice', true, 20, 'Lo que usas para escribir con tinta:', '{"options":["pen","door","chair"]}'::jsonb, 'pen', '"pen" = bolígrafo.', 20),
  (2, 'vocabulary', 5, 'multiple_choice', true, 20, 'Donde te sientas:', '{"options":["book","chair","pen"]}'::jsonb, 'chair', '"chair" = silla.', 20),
  (2, 'vocabulary', 5, 'multiple_choice', true, 20, 'Lo que lees, con páginas:', '{"options":["book","desk","window"]}'::jsonb, 'book', '"book" = libro.', 20),
  (2, 'vocabulary', 5, 'multiple_choice', true, 20, 'Lo que usas para escribir, de madera:', '{"options":["pencil","door","chair"]}'::jsonb, 'pencil', '"pencil" = lápiz.', 20),
  (2, 'vocabulary', 5, 'multiple_choice', true, 20, 'La mesa donde estudias:', '{"options":["desk","ball","car"]}'::jsonb, 'desk', '"desk" = pupitre.', 20),
  (2, 'vocabulary', 5, 'multiple_choice', true, 20, '''window'' significa:', '{"options":["silla","puerta","ventana"]}'::jsonb, 'ventana', '"window" = ventana.', 20),
  (2, 'vocabulary', 5, 'multiple_choice', true, 20, '''door'' significa:', '{"options":["mesa","ventana","puerta"]}'::jsonb, 'puerta', '"door" = puerta.', 20),
  (2, 'vocabulary', 5, 'multiple_choice', true, 20, '''book'' en español es:', '{"options":["lápiz","silla","libro"]}'::jsonb, 'libro', '"book" = libro.', 20),
  (2, 'grammar', 6, 'multiple_choice', true, 12, 'Elige: "___ teacher"', '{"options":["a","an"]}'::jsonb, 'a', '"teacher" empieza con sonido consonante → a.', 20),
  (2, 'grammar', 6, 'multiple_choice', true, 12, 'Elige: "___ dog"', '{"options":["a","an"]}'::jsonb, 'a', '"dog" empieza con sonido consonante → a.', 20),
  (2, 'grammar', 6, 'multiple_choice', true, 12, 'Elige: "___ table"', '{"options":["a","an"]}'::jsonb, 'a', '"table" empieza con sonido consonante → a.', 20),
  (2, 'grammar', 6, 'multiple_choice', true, 12, 'Elige: "___ door"', '{"options":["a","an"]}'::jsonb, 'a', '"door" empieza con sonido consonante → a.', 20),
  (2, 'grammar', 6, 'multiple_choice', true, 12, 'Elige: "___ car"', '{"options":["a","an"]}'::jsonb, 'a', '"car" empieza con sonido consonante → a.', 20),
  (2, 'grammar', 6, 'multiple_choice', true, 12, 'Elige: "___ friend"', '{"options":["an","a"]}'::jsonb, 'a', '"friend" empieza con sonido consonante → a.', 20),
  (2, 'grammar', 6, 'multiple_choice', true, 12, 'Elige: "___ boy"', '{"options":["an","a"]}'::jsonb, 'a', '"boy" empieza con sonido consonante → a.', 20),
  (2, 'grammar', 6, 'multiple_choice', true, 12, 'Elige: "___ banana"', '{"options":["a","an"]}'::jsonb, 'a', '"banana" empieza con sonido consonante → a.', 20),
  (2, 'grammar', 6, 'fill_blank', true, 12, 'Escribe a o an: "___ pen"', '{}'::jsonb, 'a', '"pen" → a.', 20),
  (2, 'grammar', 6, 'fill_blank', true, 12, 'Escribe a o an: "___ chair"', '{}'::jsonb, 'a', '"chair" → a.', 20),
  (2, 'grammar', 6, 'fill_blank', true, 12, 'Escribe a o an: "___ teacher"', '{}'::jsonb, 'a', '"teacher" → a.', 20),
  (2, 'grammar', 6, 'fill_blank', true, 12, 'Escribe a o an: "___ dog"', '{}'::jsonb, 'a', '"dog" → a.', 20),
  (2, 'grammar', 6, 'fill_blank', true, 12, 'Escribe a o an: "___ table"', '{}'::jsonb, 'a', '"table" → a.', 20),
  (2, 'grammar', 6, 'fill_blank', true, 12, 'Escribe a o an: "___ door"', '{}'::jsonb, 'a', '"door" → a.', 20);
  raise notice 'Unidad 2: 100 ejercicios sembrados.';
end $$;
