-- ============================================================
-- Contenido de PRÁCTICA - Unidad 1 "Getting to Know You" (~100 ejercicios)
-- Generado. Ejecutar después de theory_practice.sql. Idempotente a nivel de unidad.
-- Ejercicios originales A1.3 (verb to be + saludos). Auto-corregibles (sin IA).
-- ============================================================

do $$
begin
  if exists (select 1 from practice_exercises where unit_id = 1) then
    raise notice 'La unidad 1 ya tiene práctica; no se vuelve a sembrar.';
    return;
  end if;

  insert into practice_exercises (unit_id, area, level, type, timed, time_limit_seconds, prompt, payload, correct_answer, explanation, xp_reward) values
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "I ___ a student."', '{"options":["is","am","are"]}'::jsonb, 'am', 'Con "I" usamos "am".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "You ___ a student."', '{"options":["are","is","am"]}'::jsonb, 'are', 'Con "You" usamos "are".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "He ___ a student."', '{"options":["am","are","is"]}'::jsonb, 'is', 'Con "He" usamos "is".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "She ___ a student."', '{"options":["am","are","is"]}'::jsonb, 'is', 'Con "She" usamos "is".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "It ___ a student."', '{"options":["is","am","are"]}'::jsonb, 'is', 'Con "It" usamos "is".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "We ___ a student."', '{"options":["is","am","are"]}'::jsonb, 'are', 'Con "We" usamos "are".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "They ___ a student."', '{"options":["am","is","are"]}'::jsonb, 'are', 'Con "They" usamos "are".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "I ___ a teacher."', '{"options":["are","am","is"]}'::jsonb, 'am', 'Con "I" usamos "am".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "You ___ a teacher."', '{"options":["is","are","am"]}'::jsonb, 'are', 'Con "You" usamos "are".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "He ___ a teacher."', '{"options":["are","am","is"]}'::jsonb, 'is', 'Con "He" usamos "is".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "She ___ a teacher."', '{"options":["are","am","is"]}'::jsonb, 'is', 'Con "She" usamos "is".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "It ___ a teacher."', '{"options":["are","am","is"]}'::jsonb, 'is', 'Con "It" usamos "is".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "We ___ a teacher."', '{"options":["is","are","am"]}'::jsonb, 'are', 'Con "We" usamos "are".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "They ___ a teacher."', '{"options":["is","are","am"]}'::jsonb, 'are', 'Con "They" usamos "are".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "I ___ my friend."', '{"options":["is","am","are"]}'::jsonb, 'am', 'Con "I" usamos "am".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "You ___ my friend."', '{"options":["is","am","are"]}'::jsonb, 'are', 'Con "You" usamos "are".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "He ___ my friend."', '{"options":["are","am","is"]}'::jsonb, 'is', 'Con "He" usamos "is".', 10),
  (1, 'grammar', 1, 'multiple_choice', false, null, 'Completa: "She ___ my friend."', '{"options":["is","am","are"]}'::jsonb, 'is', 'Con "She" usamos "is".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "It ___ my friend."', '{"options":["is","am","are"]}'::jsonb, 'is', 'Con "It" usamos "is".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "We ___ my friend."', '{"options":["is","am","are"]}'::jsonb, 'are', 'Con "We" usamos "are".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "They ___ my friend."', '{"options":["am","are","is"]}'::jsonb, 'are', 'Con "They" usamos "are".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "I ___ happy."', '{"options":["am","are","is"]}'::jsonb, 'am', 'Con "I" usamos "am".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "You ___ happy."', '{"options":["am","is","are"]}'::jsonb, 'are', 'Con "You" usamos "are".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "He ___ happy."', '{"options":["is","am","are"]}'::jsonb, 'is', 'Con "He" usamos "is".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "She ___ happy."', '{"options":["am","is","are"]}'::jsonb, 'is', 'Con "She" usamos "is".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "It ___ happy."', '{"options":["am","are","is"]}'::jsonb, 'is', 'Con "It" usamos "is".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "We ___ happy."', '{"options":["is","am","are"]}'::jsonb, 'are', 'Con "We" usamos "are".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Completa: "They ___ happy."', '{"options":["am","is","are"]}'::jsonb, 'are', 'Con "They" usamos "are".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Forma corta de "I am":', '{"options":["He''s","I''m","You''re"]}'::jsonb, 'I''m', '"I am" → "I''m".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Forma corta de "You are":', '{"options":["I''m","He''s","You''re"]}'::jsonb, 'You''re', '"You are" → "You''re".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Forma corta de "He is":', '{"options":["I''m","He''s","You''re"]}'::jsonb, 'He''s', '"He is" → "He''s".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Forma corta de "She is":', '{"options":["You''re","I''m","She''s"]}'::jsonb, 'She''s', '"She is" → "She''s".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Forma corta de "It is":', '{"options":["It''s","I''m","You''re"]}'::jsonb, 'It''s', '"It is" → "It''s".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Forma corta de "We are":', '{"options":["We''re","You''re","I''m"]}'::jsonb, 'We''re', '"We are" → "We''re".', 10),
  (1, 'grammar', 2, 'multiple_choice', false, null, 'Forma corta de "They are":', '{"options":["You''re","I''m","They''re"]}'::jsonb, 'They''re', '"They are" → "They''re".', 10),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "I ___ tired."', '{}'::jsonb, 'am', '"I" → "am".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "You ___ tired."', '{}'::jsonb, 'are', '"You" → "are".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "He ___ tired."', '{}'::jsonb, 'is', '"He" → "is".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "She ___ tired."', '{}'::jsonb, 'is', '"She" → "is".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "It ___ tired."', '{}'::jsonb, 'is', '"It" → "is".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "We ___ tired."', '{}'::jsonb, 'are', '"We" → "are".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "They ___ tired."', '{}'::jsonb, 'are', '"They" → "are".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "I ___ ready."', '{}'::jsonb, 'am', '"I" → "am".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "You ___ ready."', '{}'::jsonb, 'are', '"You" → "are".', 15),
  (1, 'grammar', 3, 'fill_blank', false, null, 'Escribe el verbo to be: "He ___ ready."', '{}'::jsonb, 'is', '"He" → "is".', 15),
  (1, 'grammar', 3, 'multiple_choice', false, null, 'Negativo: "She ___ not ready."', '{"options":["am","are","is"]}'::jsonb, 'is', '"She" → "is" (She is not).', 15),
  (1, 'grammar', 3, 'multiple_choice', false, null, 'Negativo: "It ___ not ready."', '{"options":["is","are","am"]}'::jsonb, 'is', '"It" → "is" (It is not).', 15),
  (1, 'grammar', 3, 'multiple_choice', false, null, 'Negativo: "We ___ not ready."', '{"options":["am","is","are"]}'::jsonb, 'are', '"We" → "are" (We are not).', 15),
  (1, 'grammar', 3, 'multiple_choice', false, null, 'Negativo: "They ___ not ready."', '{"options":["am","is","are"]}'::jsonb, 'are', '"They" → "are" (They are not).', 15),
  (1, 'grammar', 3, 'multiple_choice', false, null, 'Negativo: "I ___ not kind."', '{"options":["is","am","are"]}'::jsonb, 'am', '"I" → "am" (I am not).', 15),
  (1, 'grammar', 3, 'multiple_choice', false, null, 'Negativo: "You ___ not kind."', '{"options":["am","is","are"]}'::jsonb, 'are', '"You" → "are" (You are not).', 15),
  (1, 'grammar', 3, 'multiple_choice', false, null, 'Negativo: "He ___ not kind."', '{"options":["is","am","are"]}'::jsonb, 'is', '"He" → "is" (He is not).', 15),
  (1, 'grammar', 3, 'multiple_choice', false, null, 'Negativo: "She ___ not kind."', '{"options":["am","is","are"]}'::jsonb, 'is', '"She" → "is" (She is not).', 15),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["kind","is","It"]}'::jsonb, 'It is kind', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["We","are","kind"]}'::jsonb, 'We are kind', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["They","kind","are"]}'::jsonb, 'They are kind', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["Colombia","from","am","I"]}'::jsonb, 'I am from Colombia', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["Colombia","are","You","from"]}'::jsonb, 'You are from Colombia', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["He","Colombia","is","from"]}'::jsonb, 'He is from Colombia', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["is","from","She","Colombia"]}'::jsonb, 'She is from Colombia', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["Colombia","from","It","is"]}'::jsonb, 'It is from Colombia', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["Colombia","are","We","from"]}'::jsonb, 'We are from Colombia', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["Colombia","from","They","are"]}'::jsonb, 'They are from Colombia', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["I","am","Mexico","from"]}'::jsonb, 'I am from Mexico', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["You","are","Mexico","from"]}'::jsonb, 'You are from Mexico', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["is","He","Mexico","from"]}'::jsonb, 'He is from Mexico', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["from","is","Mexico","She"]}'::jsonb, 'She is from Mexico', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["It","is","from","Mexico"]}'::jsonb, 'It is from Mexico', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["are","Mexico","We","from"]}'::jsonb, 'We are from Mexico', 'Sujeto + verbo to be + complemento.', 20),
  (1, 'grammar', 5, 'true_false', true, 20, '''I am happy'' is correct.', '{}'::jsonb, 'true', 'Correcto: I am happy.', 20),
  (1, 'grammar', 5, 'true_false', true, 20, '''She are my friend'' is correct.', '{}'::jsonb, 'false', 'Lo correcto es: She is my friend.', 20),
  (1, 'grammar', 5, 'true_false', true, 20, '''They are students'' is correct.', '{}'::jsonb, 'true', 'Correcto: They are students.', 20),
  (1, 'grammar', 5, 'true_false', true, 20, '''He am tired'' is correct.', '{}'::jsonb, 'false', 'Lo correcto es: He is tired.', 20),
  (1, 'grammar', 5, 'true_false', true, 20, '''We are ready'' is correct.', '{}'::jsonb, 'true', 'Correcto: We are ready.', 20),
  (1, 'grammar', 5, 'true_false', true, 20, '''You is kind'' is correct.', '{}'::jsonb, 'false', 'Lo correcto es: You are kind.', 20),
  (1, 'grammar', 5, 'true_false', true, 20, '''It is a pen'' is correct.', '{}'::jsonb, 'true', 'Correcto: It is a pen.', 20),
  (1, 'grammar', 5, 'true_false', true, 20, '''I are here'' is correct.', '{}'::jsonb, 'false', 'Lo correcto es: I am here.', 20),
  (1, 'vocabulary', 5, 'multiple_choice', true, 20, '¿Cuál es un saludo?', '{"options":["Table","Run","Hello"]}'::jsonb, 'Hello', '"Hello" = hola.', 20),
  (1, 'vocabulary', 5, 'multiple_choice', true, 20, 'Cuando te vas dices:', '{"options":["Friend","Goodbye","Name"]}'::jsonb, 'Goodbye', '"Goodbye" = adiós.', 20),
  (1, 'vocabulary', 5, 'multiple_choice', true, 20, '''Name'' significa:', '{"options":["casa","libro","nombre"]}'::jsonb, 'nombre', '"Name" = nombre.', 20),
  (1, 'vocabulary', 5, 'multiple_choice', true, 20, '''What is your ___?'' (preguntar el nombre)', '{"options":["name","friend","teacher"]}'::jsonb, 'name', 'Se pregunta "What is your name?".', 20),
  (1, 'vocabulary', 5, 'multiple_choice', true, 20, '''Hello'' en español es:', '{"options":["Adiós","Hola","Gracias"]}'::jsonb, 'Hola', '"Hello" = hola.', 20),
  (1, 'vocabulary', 5, 'multiple_choice', true, 20, 'Una persona que enseña es un/una:', '{"options":["student","teacher","friend"]}'::jsonb, 'teacher', '"Teacher" = profesor/profesora.', 20),
  (1, 'vocabulary', 5, 'multiple_choice', true, 20, '''Friend'' significa:', '{"options":["enemigo","maestro","amigo"]}'::jsonb, 'amigo', '"Friend" = amigo/amiga.', 20),
  (1, 'vocabulary', 5, 'multiple_choice', true, 20, 'Para despedirte dices:', '{"options":["Name","Goodbye","Hello"]}'::jsonb, 'Goodbye', '"Goodbye" = adiós.', 20),
  (1, 'grammar', 6, 'multiple_choice', true, 12, 'Completa: "They ___ from Mexico."', '{"options":["am","are","is"]}'::jsonb, 'are', 'Con "They" usamos "are".', 20),
  (1, 'grammar', 6, 'multiple_choice', true, 12, 'Completa: "I ___ from Brazil."', '{"options":["are","is","am"]}'::jsonb, 'am', 'Con "I" usamos "am".', 20),
  (1, 'grammar', 6, 'multiple_choice', true, 12, 'Completa: "You ___ from Brazil."', '{"options":["are","am","is"]}'::jsonb, 'are', 'Con "You" usamos "are".', 20),
  (1, 'grammar', 6, 'multiple_choice', true, 12, 'Completa: "He ___ from Brazil."', '{"options":["is","am","are"]}'::jsonb, 'is', 'Con "He" usamos "is".', 20),
  (1, 'grammar', 6, 'multiple_choice', true, 12, 'Completa: "She ___ from Brazil."', '{"options":["is","am","are"]}'::jsonb, 'is', 'Con "She" usamos "is".', 20),
  (1, 'grammar', 6, 'multiple_choice', true, 12, 'Completa: "It ___ from Brazil."', '{"options":["am","are","is"]}'::jsonb, 'is', 'Con "It" usamos "is".', 20),
  (1, 'grammar', 6, 'multiple_choice', true, 12, 'Completa: "We ___ from Brazil."', '{"options":["is","am","are"]}'::jsonb, 'are', 'Con "We" usamos "are".', 20),
  (1, 'grammar', 6, 'multiple_choice', true, 12, 'Completa: "They ___ from Brazil."', '{"options":["are","am","is"]}'::jsonb, 'are', 'Con "They" usamos "are".', 20),
  (1, 'grammar', 6, 'fill_blank', true, 12, 'Escribe el verbo to be: "I ___ at school."', '{}'::jsonb, 'am', '"I" → "am".', 20),
  (1, 'grammar', 6, 'fill_blank', true, 12, 'Escribe el verbo to be: "You ___ at school."', '{}'::jsonb, 'are', '"You" → "are".', 20),
  (1, 'grammar', 6, 'fill_blank', true, 12, 'Escribe el verbo to be: "He ___ at school."', '{}'::jsonb, 'is', '"He" → "is".', 20),
  (1, 'grammar', 6, 'fill_blank', true, 12, 'Escribe el verbo to be: "She ___ at school."', '{}'::jsonb, 'is', '"She" → "is".', 20),
  (1, 'grammar', 6, 'fill_blank', true, 12, 'Escribe el verbo to be: "It ___ at school."', '{}'::jsonb, 'is', '"It" → "is".', 20),
  (1, 'grammar', 6, 'fill_blank', true, 12, 'Escribe el verbo to be: "We ___ at school."', '{}'::jsonb, 'are', '"We" → "are".', 20);

  raise notice 'Unidad 1: 99 ejercicios de práctica sembrados.';
end $$;
