-- Práctica Unidad 4 "A Normal Day" (~100, original A1.3). Idempotente.
do $$
begin
  if exists (select 1 from practice_exercises where unit_id = 4) then
    raise notice 'La unidad 4 ya tiene práctica.'; return;
  end if;
  insert into practice_exercises (unit_id, area, level, type, timed, time_limit_seconds, prompt, payload, correct_answer, explanation, xp_reward) values
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ every day. (work)', '{"options":["work","works","workes"]}'::jsonb, 'works', 'Con He el verbo lleva terminación: works.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ TV. (watch)', '{"options":["watches","watch","watchs"]}'::jsonb, 'watches', 'Con He el verbo lleva terminación: watches.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ English. (study)', '{"options":["study","studys","studies"]}'::jsonb, 'studies', 'Con He el verbo lleva terminación: studies.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ breakfast. (eat)', '{"options":["eat","eats","eates"]}'::jsonb, 'eats', 'Con He el verbo lleva terminación: eats.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ the car. (wash)', '{"options":["wash","washes","washs"]}'::jsonb, 'washes', 'Con He el verbo lleva terminación: washes.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ the test. (finish)', '{"options":["finishs","finish","finishes"]}'::jsonb, 'finishes', 'Con He el verbo lleva terminación: finishes.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ every day. (work)', '{"options":["works","workes","work"]}'::jsonb, 'works', 'Con He el verbo lleva terminación: works.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ TV. (watch)', '{"options":["watch","watches","watchs"]}'::jsonb, 'watches', 'Con He el verbo lleva terminación: watches.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ English. (study)', '{"options":["studys","study","studies"]}'::jsonb, 'studies', 'Con He el verbo lleva terminación: studies.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ breakfast. (eat)', '{"options":["eates","eat","eats"]}'::jsonb, 'eats', 'Con He el verbo lleva terminación: eats.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ the car. (wash)', '{"options":["washs","wash","washes"]}'::jsonb, 'washes', 'Con He el verbo lleva terminación: washes.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ the test. (finish)', '{"options":["finish","finishes","finishs"]}'::jsonb, 'finishes', 'Con He el verbo lleva terminación: finishes.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ every day. (work)', '{"options":["works","work","workes"]}'::jsonb, 'works', 'Con He el verbo lleva terminación: works.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ TV. (watch)', '{"options":["watch","watchs","watches"]}'::jsonb, 'watches', 'Con He el verbo lleva terminación: watches.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ English. (study)', '{"options":["study","studies","studys"]}'::jsonb, 'studies', 'Con He el verbo lleva terminación: studies.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ breakfast. (eat)', '{"options":["eates","eats","eat"]}'::jsonb, 'eats', 'Con He el verbo lleva terminación: eats.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ the car. (wash)', '{"options":["washes","wash","washs"]}'::jsonb, 'washes', 'Con He el verbo lleva terminación: washes.', 10),
  (4, 'grammar', 1, 'multiple_choice', false, null, 'He ___ the test. (finish)', '{"options":["finish","finishes","finishs"]}'::jsonb, 'finishes', 'Con He el verbo lleva terminación: finishes.', 10),
  (4, 'grammar', 2, 'multiple_choice', false, null, 'It ___ every day. (work)', '{"options":["workes","work","works"]}'::jsonb, 'works', 'Con It el verbo lleva terminación: works.', 10),
  (4, 'grammar', 2, 'multiple_choice', false, null, 'You ___ TV. (watch)', '{"options":["watches","watchs","watch"]}'::jsonb, 'watch', 'Con You el verbo no cambia: watch.', 10),
  (4, 'grammar', 2, 'multiple_choice', false, null, 'They ___ English. (study)', '{"options":["studies","studys","study"]}'::jsonb, 'study', 'Con They el verbo no cambia: study.', 10),
  (4, 'grammar', 2, 'multiple_choice', false, null, 'He ___ breakfast. (eat)', '{"options":["eats","eates","eat"]}'::jsonb, 'eats', 'Con He el verbo lleva terminación: eats.', 10),
  (4, 'grammar', 2, 'multiple_choice', false, null, 'I ___ the car. (wash)', '{"options":["wash","washes","washs"]}'::jsonb, 'wash', 'Con I el verbo no cambia: wash.', 10),
  (4, 'grammar', 2, 'multiple_choice', false, null, 'We ___ the test. (finish)', '{"options":["finish","finishes","finishs"]}'::jsonb, 'finish', 'Con We el verbo no cambia: finish.', 10),
  (4, 'grammar', 2, 'multiple_choice', false, null, 'She ___ every day. (work)', '{"options":["work","workes","works"]}'::jsonb, 'works', 'Con She el verbo lleva terminación: works.', 10),
  (4, 'grammar', 2, 'multiple_choice', false, null, 'It ___ TV. (watch)', '{"options":["watch","watchs","watches"]}'::jsonb, 'watches', 'Con It el verbo lleva terminación: watches.', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, '''get up'' significa:', '{"options":["levantarse","dormir","desayunar"]}'::jsonb, 'levantarse', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, '''have breakfast'' significa:', '{"options":["desayunar","cenar","almorzar"]}'::jsonb, 'desayunar', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, 'Lavar tu cuerpo con agua:', '{"options":["get up","do homework","take a shower"]}'::jsonb, 'take a shower', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, '''do homework'' significa:', '{"options":["hacer la tarea","ir a la escuela","jugar"]}'::jsonb, 'hacer la tarea', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, '''go to school'' significa:', '{"options":["ir a la escuela","dormir","ir a casa"]}'::jsonb, 'ir a la escuela', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, 'Donde cocinas:', '{"options":["bathroom","kitchen","bedroom"]}'::jsonb, 'kitchen', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, 'Donde duermes:', '{"options":["kitchen","bedroom","garden"]}'::jsonb, 'bedroom', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, 'Donde te duchas:', '{"options":["living room","bathroom","kitchen"]}'::jsonb, 'bathroom', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, 'Donde la familia ve TV:', '{"options":["garden","bedroom","living room"]}'::jsonb, 'living room', '', 10),
  (4, 'vocabulary', 2, 'multiple_choice', false, null, '''garden'' significa:', '{"options":["cocina","jardín","baño"]}'::jsonb, 'jardín', '"garden" = jardín.', 10),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "You ___ English." (study)', '{}'::jsonb, 'study', 'You → study.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "They ___ breakfast." (eat)', '{}'::jsonb, 'eat', 'They → eat.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "He ___ the car." (wash)', '{}'::jsonb, 'washes', 'He → washes.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "I ___ the test." (finish)', '{}'::jsonb, 'finish', 'I → finish.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "We ___ every day." (work)', '{}'::jsonb, 'work', 'We → work.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "She ___ TV." (watch)', '{}'::jsonb, 'watches', 'She → watches.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "It ___ English." (study)', '{}'::jsonb, 'studies', 'It → studies.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "You ___ breakfast." (eat)', '{}'::jsonb, 'eat', 'You → eat.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "They ___ the car." (wash)', '{}'::jsonb, 'wash', 'They → wash.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "He ___ the test." (finish)', '{}'::jsonb, 'finishes', 'He → finishes.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "I ___ every day." (work)', '{}'::jsonb, 'work', 'I → work.', 15),
  (4, 'grammar', 3, 'fill_blank', false, null, 'Presente simple: "We ___ TV." (watch)', '{}'::jsonb, 'watch', 'We → watch.', 15),
  (4, 'vocabulary', 3, 'multiple_choice', false, null, 'Lavar tu cuerpo con agua:', '{"options":["get up","take a shower","do homework"]}'::jsonb, 'take a shower', '', 15),
  (4, 'vocabulary', 3, 'multiple_choice', false, null, '''do homework'' significa:', '{"options":["ir a la escuela","hacer la tarea","jugar"]}'::jsonb, 'hacer la tarea', '', 15),
  (4, 'vocabulary', 3, 'multiple_choice', false, null, '''go to school'' significa:', '{"options":["ir a casa","dormir","ir a la escuela"]}'::jsonb, 'ir a la escuela', '', 15),
  (4, 'vocabulary', 3, 'multiple_choice', false, null, 'Donde cocinas:', '{"options":["bathroom","kitchen","bedroom"]}'::jsonb, 'kitchen', '', 15),
  (4, 'vocabulary', 3, 'multiple_choice', false, null, 'Donde duermes:', '{"options":["kitchen","bedroom","garden"]}'::jsonb, 'bedroom', '', 15),
  (4, 'vocabulary', 3, 'multiple_choice', false, null, 'Donde te duchas:', '{"options":["living room","kitchen","bathroom"]}'::jsonb, 'bathroom', '', 15),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["studies","English","He"]}'::jsonb, 'He studies English', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["They","breakfast","eat"]}'::jsonb, 'They eat breakfast', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["washes","car","He","the"]}'::jsonb, 'He washes the car', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["the","finish","They","test"]}'::jsonb, 'They finish the test', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["day","every","works","He"]}'::jsonb, 'He works every day', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["They","watch","TV"]}'::jsonb, 'They watch TV', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["English","He","studies"]}'::jsonb, 'He studies English', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["eat","breakfast","They"]}'::jsonb, 'They eat breakfast', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["He","the","car","washes"]}'::jsonb, 'He washes the car', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["test","finish","the","They"]}'::jsonb, 'They finish the test', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["works","every","day","He"]}'::jsonb, 'He works every day', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["watch","TV","They"]}'::jsonb, 'They watch TV', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["English","studies","He"]}'::jsonb, 'He studies English', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["eat","They","breakfast"]}'::jsonb, 'They eat breakfast', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["car","washes","the","He"]}'::jsonb, 'He washes the car', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'writing', 4, 'reorder', true, 30, 'Ordena para formar la oración:', '{"words":["finish","They","the","test"]}'::jsonb, 'They finish the test', 'Sujeto + verbo (presente simple) + complemento.', 20),
  (4, 'grammar', 5, 'true_false', true, 20, '''She work every day'' is correct.', '{}'::jsonb, 'false', 'Lo correcto: She works.', 20),
  (4, 'grammar', 5, 'true_false', true, 20, '''He goes to school'' is correct.', '{}'::jsonb, 'true', 'Correcto.', 20),
  (4, 'grammar', 5, 'true_false', true, 20, '''They plays soccer'' is correct.', '{}'::jsonb, 'false', 'Lo correcto: They play.', 20),
  (4, 'grammar', 5, 'true_false', true, 20, '''She studies English'' is correct.', '{}'::jsonb, 'true', 'Correcto.', 20),
  (4, 'grammar', 5, 'true_false', true, 20, '''I works here'' is correct.', '{}'::jsonb, 'false', 'Lo correcto: I work.', 20),
  (4, 'grammar', 5, 'true_false', true, 20, '''He watches TV'' is correct.', '{}'::jsonb, 'true', 'Correcto.', 20),
  (4, 'grammar', 5, 'true_false', true, 20, '''We goes home'' is correct.', '{}'::jsonb, 'false', 'Lo correcto: We go.', 20),
  (4, 'grammar', 5, 'true_false', true, 20, '''She carries a bag'' is correct.', '{}'::jsonb, 'true', 'Correcto.', 20),
  (4, 'vocabulary', 5, 'multiple_choice', true, 20, 'Donde cocinas:', '{"options":["bedroom","kitchen","bathroom"]}'::jsonb, 'kitchen', '', 20),
  (4, 'vocabulary', 5, 'multiple_choice', true, 20, 'Donde duermes:', '{"options":["bedroom","garden","kitchen"]}'::jsonb, 'bedroom', '', 20),
  (4, 'vocabulary', 5, 'multiple_choice', true, 20, 'Donde te duchas:', '{"options":["living room","kitchen","bathroom"]}'::jsonb, 'bathroom', '', 20),
  (4, 'vocabulary', 5, 'multiple_choice', true, 20, 'Donde la familia ve TV:', '{"options":["garden","bedroom","living room"]}'::jsonb, 'living room', '', 20),
  (4, 'vocabulary', 5, 'multiple_choice', true, 20, '''garden'' significa:', '{"options":["jardín","baño","cocina"]}'::jsonb, 'jardín', '"garden" = jardín.', 20),
  (4, 'vocabulary', 5, 'multiple_choice', true, 20, '''kitchen'' significa:', '{"options":["cocina","baño","sala"]}'::jsonb, 'cocina', '', 20),
  (4, 'vocabulary', 5, 'multiple_choice', true, 20, '''bedroom'' significa:', '{"options":["dormitorio","jardín","cocina"]}'::jsonb, 'dormitorio', '', 20),
  (4, 'vocabulary', 5, 'multiple_choice', true, 20, '''get up'' significa:', '{"options":["desayunar","dormir","levantarse"]}'::jsonb, 'levantarse', '', 20),
  (4, 'grammar', 6, 'multiple_choice', true, 12, 'You ___ every day. (work)', '{"options":["workes","works","work"]}'::jsonb, 'work', 'Con You el verbo no cambia: work.', 20),
  (4, 'grammar', 6, 'multiple_choice', true, 12, 'They ___ TV. (watch)', '{"options":["watches","watchs","watch"]}'::jsonb, 'watch', 'Con They el verbo no cambia: watch.', 20),
  (4, 'grammar', 6, 'multiple_choice', true, 12, 'He ___ English. (study)', '{"options":["study","studys","studies"]}'::jsonb, 'studies', 'Con He el verbo lleva terminación: studies.', 20),
  (4, 'grammar', 6, 'multiple_choice', true, 12, 'I ___ breakfast. (eat)', '{"options":["eat","eates","eats"]}'::jsonb, 'eat', 'Con I el verbo no cambia: eat.', 20),
  (4, 'grammar', 6, 'multiple_choice', true, 12, 'We ___ the car. (wash)', '{"options":["wash","washes","washs"]}'::jsonb, 'wash', 'Con We el verbo no cambia: wash.', 20),
  (4, 'grammar', 6, 'multiple_choice', true, 12, 'She ___ the test. (finish)', '{"options":["finish","finishes","finishs"]}'::jsonb, 'finishes', 'Con She el verbo lleva terminación: finishes.', 20),
  (4, 'grammar', 6, 'multiple_choice', true, 12, 'It ___ every day. (work)', '{"options":["workes","works","work"]}'::jsonb, 'works', 'Con It el verbo lleva terminación: works.', 20),
  (4, 'grammar', 6, 'multiple_choice', true, 12, 'You ___ TV. (watch)', '{"options":["watches","watchs","watch"]}'::jsonb, 'watch', 'Con You el verbo no cambia: watch.', 20),
  (4, 'grammar', 6, 'fill_blank', true, 12, 'Presente simple: "They ___ English." (study)', '{}'::jsonb, 'study', 'They → study.', 20),
  (4, 'grammar', 6, 'fill_blank', true, 12, 'Presente simple: "He ___ breakfast." (eat)', '{}'::jsonb, 'eats', 'He → eats.', 20),
  (4, 'grammar', 6, 'fill_blank', true, 12, 'Presente simple: "I ___ the car." (wash)', '{}'::jsonb, 'wash', 'I → wash.', 20),
  (4, 'grammar', 6, 'fill_blank', true, 12, 'Presente simple: "We ___ the test." (finish)', '{}'::jsonb, 'finish', 'We → finish.', 20),
  (4, 'grammar', 6, 'fill_blank', true, 12, 'Presente simple: "She ___ every day." (work)', '{}'::jsonb, 'works', 'She → works.', 20),
  (4, 'grammar', 6, 'fill_blank', true, 12, 'Presente simple: "It ___ TV." (watch)', '{}'::jsonb, 'watches', 'It → watches.', 20);
  raise notice 'Unidad 4: 100 ejercicios sembrados.';
end $$;
