import type { Config } from 'tailwindcss'
const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Legacy (no romper componentes antiguos)
        'best-blue': '#1e40af',
        'best-green': '#16a34a',
        'best-yellow': '#ca8a04',
        'best-red': '#dc2626',
        'best-purple': '#7c3aed',
        // ---- Neo-Arcade Edu-Tech (Stitch) ----
        background: '#0e1323',
        surface: '#0e1323',
        'surface-dim': '#0e1323',
        'surface-bright': '#34394a',
        'surface-container-lowest': '#080d1d',
        'surface-container-low': '#161b2b',
        'surface-container': '#1a1f30',
        'surface-container-high': '#25293a',
        'surface-container-highest': '#2f3446',
        'surface-variant': '#2f3446',
        'on-surface': '#dee1f9',
        'on-surface-variant': '#ccc3d8',
        'on-background': '#dee1f9',
        'inverse-surface': '#dee1f9',
        'inverse-on-surface': '#2b3041',
        outline: '#958da1',
        'outline-variant': '#4a4455',
        primary: '#d2bbff',
        'on-primary': '#3f008e',
        'primary-container': '#7c3aed',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#732ee4',
        secondary: '#5de6ff',
        'on-secondary': '#00363e',
        'secondary-container': '#00cbe6',
        'on-secondary-container': '#00515d',
        tertiary: '#98da27',
        'on-tertiary': '#213600',
        'tertiary-container': '#4b7200',
        'on-tertiary-container': '#b6fb49',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        'display-lg': ['var(--font-display)'],
        'headline-md': ['var(--font-display)'],
        'button-text': ['var(--font-display)'],
        'body-md': ['var(--font-inter)'],
        'body-lg': ['var(--font-inter)'],
        'stat-label': ['var(--font-stat)'],
        display: ['var(--font-display)'],
        body: ['var(--font-inter)'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'stat-label': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'button-text': ['16px', { lineHeight: '20px', fontWeight: '600' }],
      },
      spacing: {
        'margin-edge': '40px',
        gutter: '24px',
      },
      maxWidth: {
        shell: '1280px',
      },
    },
  },
  plugins: [],
}
export default config
